name: Mirror to Codeberg

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  mirror:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - uses: webfactory/ssh-agent@v0.9.0
        with:
          ssh-private-key: ${{ secrets.CODEBERG_SSH_KEY }}

      - name: Add Codeberg host key
        run: |
          mkdir -p ~/.ssh
          ssh-keyscan codeberg.org >> ~/.ssh/known_hosts

      - name: Add Codeberg remote
        run: |
          git remote add codeberg git@codeberg.org:krush62/KPix.git

      - name: Push branches
        run: |
          git push codeberg --all

      - name: Push tags
        run: |
          git push codeberg --tags